### ISSUE TITLE
Installing globally doesn't work

### ISSUE THREAD

**Issue by JohnMcLear** [Loophole-Labs/parasite#1]
When you install with ``sudo npm install -g @loophole-labs/parasite``
then do ``parasite`` it errors with 

```
jose@server:~$ parasite
/usr/bin/parasite: line 1: syntax error near unexpected token `('
/usr/bin/parasite: line 1: `const Parasite = require('./index');'
```

Cloning then using ``npm install`` also returns
```
jose@server:~/parasite$ parasite
/usr/bin/parasite: line 1: syntax error near unexpected token `('
/usr/bin/parasite: line 1: `const Parasite = require('./index');'
```

My env:
```
jose@server:~/parasite$ node -v
v13.10.1
```
Ubuntu something, modern enough..  Feels like I'm missing some undocumented hipster juice...

**Comment by ShivanshVij** [comment]
Parasite isn't supported globally yet (I haven't gotten around to writing the cli properly but I'm expecting to release that later this month). 

You can find out all the supported use cases here https://parasite.sh

**Comment by JohnMcLear** [comment]
Lol.  Document what IS supported then.....

**Comment by ShivanshVij** [comment]
This is all an initial release. This open source project is still under development and the best way for us to fix things is to get feedback.
