### ISSUE TITLE
Web UI only binds to localhost

### ISSUE THREAD

**Issue by JohnMcLear** [Loophole-Labs/parasite#3]
If you are debugging remotely this makes no sense?  Just bind to *

**Comment by ShivanshVij** [comment]
I'm really sorry for the confusion, we're actually hosting complete documentation and usage here: https://parasite.sh . I'll leave your issue open for now in case you need more help, but that should walk you through basic setup as well as programmatic usage, using the backend API directly, and the web UI - as well as how to make it bind to *

**Comment by JohnMcLear** [comment]
I read the docs and have things working but I don't see any option in the UI to replay.  The docs say you can from the UI.

**Comment by ShivanshVij** [comment]
Just click on a request in the table when it comes in. You'll see a modal appear with a replay button at the top.
