### ISSUE TITLE
The documentation link returns a blank page

### ISSUE THREAD

**Issue by JohnMcLear** [Loophole-Labs/parasite#4]
Clicking "Documentation" within the web view directs to 

https://github.com/Loophole-Labs/parasite/blob/master/Documentation/DOCUMENTATION.md

which is blank.

**Comment by ShivanshVij** [comment]
I'm really sorry for the confusion, we're actually hosting complete documentation and usage here: https://parasite.sh . I'll leave your other issues open in case you need more help, but that should walk you through basic setup as well as programmatic usage, using the backend API directly, and the web UI - as well as how to make it bind to `*`

**Comment by JohnMcLear** [comment]
There isn't any confusion.  Your link in your software is wrong.

**Comment by ShivanshVij** [comment]
Which link are you referring to?

**Comment by ShivanshVij** [comment]
The links in the executable are correct: https://github.com/Loophole-Labs/parasite/blob/master/executable.js#L44 as well as our README.
