### ISSUE TITLE
How do you run replays?

### ISSUE THREAD

**Issue by JohnMcLear** [Loophole-Labs/parasite#5]
After a decent amount of workarounds I finally got the software working, I gathered data and was looking for a way to replay, which is kinda the point right?  But I can't see it..

I'm hoping to do replay of each API request but changing parameters (but keeping some URI parameters static IE APIKey in my stance...

Am I missing something?

I can't use the programmatic interface because the node module doesn't work

**Comment by ShivanshVij** [comment]
I'm really sorry for the confusion, we're actually hosting complete documentation and usage here: https://parasite.sh . I'll leave your issue open for now in case you need more help, but that should walk you through basic setup as well as programmatic usage, using the backend API directly, and the web UI - as well as how to make it bind to `*`
